### ISSUE TITLE
Missing dependency to browserify

### ISSUE THREAD

**Issue by lapawa** [ags131/node-ld#12]
You've included the module in gulpfile.js but my 'npm install' call bails out with these messages:

zarq@kiwi:~/git/github/ags131/node-ld$ npm install
npm WARN package.json node-ld@1.1.2 No repository field.

> node-ld@1.1.2 prepublish /mnt/host/shared/git/github/ags131/node-ld
> gulp

module.js:327
    throw err;
    ^

Error: Cannot find module 'browserify'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/mnt/host/shared/git/github/ags131/node-ld/gulpfile.js:7:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

npm ERR! Linux 3.13.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! node-ld@1.1.2 prepublish: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-ld@1.1.2 prepublish script 'gulp'.
npm ERR! This is most likely a problem with the node-ld package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-ld
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-ld
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/host/shared/git/github/ags131/node-ld/npm-debug.log

**Comment by ags131** [comment]
Fixed in #13
