### ISSUE TITLE
Got driver installed but can't connect to toypad device.

### ISSUE THREAD

**Issue by matthewbullweb** [ags131/node-ld#5]
this._raw = new (Function.prototype.bind.apply(binding.HID,
                    ^

Error: cannot open device with vendor id 0xe6f and product id 0x241
    at Error (native)
    at new HID (C:\Users\Matt\Downloads\node-ld-master\node-ld\node_modules\node-hid\nodehid.js:28:14)
    at new HIDTransport (C:\Users\Matt\Downloads\node-ld-master\node-ld\transports\hid.js:12:24)
    at Object.<anonymous> (C:\Users\Matt\Downloads\node-ld-master\node-ld\samples\demo.js:7:17)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)

**Comment by ags131** [comment]
When using the default HID transport the Zadig method isn't needed. If using the Zadig method, you have to use the libusb transport. You can either use the libusbtransport or uninstall the libusb driver through device manager, (Make sure to check "delete this driver")

**Comment by matthewbullweb** [comment]
Thank you. Did that and now get can't write to HID device with a payload value.

**Comment by ags131** [comment]
What console is the portal from? And what error are you getting?

**Comment by matthewbullweb** [comment]
This is for a PS3. My error output for both scripts is below.

C:\Users\Matt\Downloads\node-ld-master\node-ld\samples>node demo.js
Error: Cannot write to HID device
    at Error (native)
    at HIDTransport.writeData [as write] (C:\Users\Matt\Downloads\node-ld-master\node-ld\transports\hid.js:53:13)
    at Object.<anonymous> (C:\Users\Matt\Downloads\node-ld-master\node-ld\samples\demo.js:32:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
    at node.js:952:3
clean

C:\Users\Matt\Downloads\node-ld-master\node-ld\samples>node toypadDemo.js
REQ Request {
  cmd: 176,
  cid: 1,
  payload: <Buffer 28 63 29 20 4c 45 47 4f 20 32 30 31 34> }
C:\Users\Matt\Downloads\node-ld-master\node-ld\transports\hid.js:53
          self.dev.write(buffer)
                   ^

Error: Cannot write to HID device
    at Error (native)
    at HIDTransport.writeData [as write] (C:\Users\Matt\Downloads\node-ld-master\node-ld\transports\hid.js:53:13)
    at ToyPad._write (C:\Users\Matt\Downloads\node-ld-master\node-ld\lib\ToyPad.js:48:18)
    at ToyPad.request (C:\Users\Matt\Downloads\node-ld-master\node-ld\lib\ToyPad.js:76:7)
    at ToyPad.wake (C:\Users\Matt\Downloads\node-ld-master\node-ld\lib\ToyPad.js:100:7)
    at Object.<anonymous> (C:\Users\Matt\Downloads\node-ld-master\node-ld\samples\toypadDemo.js:15:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by ags131** [comment]
Try commenting out Line 50 of transports/hid.js and see if it works then, if it does, then Windows is entirely inconsistent. ^.^

**Comment by matthewbullweb** [comment]
Had to comment out lines 50 to 54 in hid.js and got the following.

C:\Users\Matt\Downloads\node-ld-master\node-ld>node samples\toypaddemo.js
REQ Request {
  cmd: 176,
  cid: 1,
  payload: <Buffer 28 63 29 20 4c 45 47 4f 20 32 30 31 34> }
REQ Request { cmd: 192, cid: 2, payload: <Buffer 00 ff ff ff> }
REQ Request { cmd: 192, cid: 3, payload: <Buffer 01 ff 00 00> }
REQ Request { cmd: 192, cid: 4, payload: <Buffer 02 00 ff 00> }
REQ Request { cmd: 192, cid: 5, payload: <Buffer 03 00 00 ff> }
REQ Request {
  cmd: 198,
  cid: 6,
  payload: <Buffer 01 19 01 00 00 00 01 19 01 00 00 00 01 19 01 00 00 00> }
REQ Request {
  cmd: 198,
  cid: 7,
  payload: <Buffer 01 19 01 ff 00 00 01 19 01 00 ff 00 01 19 01 00 00 ff> }
REQ Request {
  cmd: 198,
  cid: 8,
  payload: <Buffer 01 19 01 00 ff 00 01 19 01 00 00 ff 01 19 01 ff 00 00> }
REQ Request {
  cmd: 198,
  cid: 9,
  payload: <Buffer 01 19 01 00 00 ff 01 19 01 ff 00 00 01 19 01 00 ff 00> }
REQ Request {
  cmd: 198,
  cid: 10,
  payload: <Buffer 01 19 01 ff 00 00 01 19 01 00 ff 00 01 19 01 00 00 ff> }
REQ Request {
  cmd: 198,
  cid: 11,
  payload: <Buffer 01 19 01 00 00 00 01 19 01 00 00 00 01 19 01 00 00 00> }
REQ Request {
  cmd: 198,
  cid: 12,
  payload: <Buffer 01 19 0a 00 ff 00 01 19 0a 00 ff 00 01 19 0a 00 ff 00> }

**Comment by ags131** [comment]
Without 53 it won't actually send the data to the device, did it work after commenting 50?
Another thought I just had, may also try running as admin, it could be permissions issues

**Comment by matthewbullweb** [comment]
Unfortunately not; the write command is want causes it to fail. Did console.log out self.dev and buffer.

self.dev HID {
  domain: null,
  _events:
   { newListener: [Function],
     data: [Function: receiveData],
     error: [Function: receiveError] },
  _eventsCount: 3,
  _maxListeners: undefined,
  _raw: HID {},
  read: [Function: bound read],
  write: [Function: bound write],
  getFeatureReport: [Function: bound getFeatureReport],
  sendFeatureReport: [Function: bound sendFeatureReport],
  setNonBlocking: [Function: bound setNonBlocking],
  _paused: false }

buffer [ 0,
  85,
  15,
  176,
  0,
  40,
  99,
  41,
  32,
  76,
  69,
  71,
  79,
  32,
  50,
  48,
  49,
  52,
  246,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0 ]

**Comment by ags131** [comment]
I'm out of ideas, I'll plug mine in when I get home and see if I can replicate and if so, figure out a fix, The hid class and buffer look fine as far as I can tell.

**Comment by matthewbullweb** [comment]
Appreciate your time. Will be looking forward to seeing if its possable to use this toypad away from game consoles.

**Comment by ags131** [comment]
Ok, I was able to get it working here, I do get the cannot write error, but after attempting to run the app again once or twice it works. I'm not quite sure whats going on. I'm going to keep poking at it and see if i can figure out why it fails some times and not others.

**Comment by matthewbullweb** [comment]
Managed to get this working with method mentioned. Notice pad lights flash on first try but script does not latch. Its like it needs time to detect the pad has been woken.

**Comment by ags131** [comment]
Try this, https://gist.github.com/ags131/c70a333e552403802c73 I wrapped most of the code in a setTimeout, see if that helps. The toypad will almost always flash white once when plugged in, but this should trigger many different colors and patterns.

**Comment by ags131** [comment]
This should be fixed as of 8a62562
